
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/websocket-enabled: "true"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: sahil-ingress-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:947557066309:certificate/8b2350e9-30c6-4ec4-bf9b-4b766562edf4
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600
    alb.ingress.kubernetes.io/actions.static-response: >
      {"Type":"fixed-response","FixedResponseConfig":{"ContentType":"text/plain","StatusCode":"200","MessageBody":"OK"}}
spec:
  ingressClassName: alb
  rules:
    - host: nodejs.sahil.virals.studio
      http:
        paths:
          - path: /health
            pathType: Exact
            backend:
              service:
                name: static-response
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-backend-service
                port:
                  number: 80
          - path: /socket
            pathType: Prefix
            backend:
              service:
                name: node-backend-service
                port:
                  number: 80

