

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: database
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.image.mongodb }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.rootUser | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.rootPassword | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.database | quote }}
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: database
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
