
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis1
  namespace: database
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis1
  template:
    metadata:
      labels:
        app: redis1
    spec:
      containers:
        - name: redis
          image: {{ .Values.image.redis }}
          ports:
            - containerPort:  6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis1
  namespace: database
spec:
  selector:
    app: redis1
  ports:
    - port:  6379
      targetPort: 6379
      protocol: TCP

       
